version: '3'
services:
  frontend-sght:
    container_name: frontend-sght
    restart: always
    build: ../front-sght/.
    ports:
      - 5174:80
    networks:
      - sght-net

  spring-sght:
    build: .
    container_name: back-spring
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://24.144.93.247:5432/sght_db
      - SPRING_DATASOURCE_USERNAME=sght_user
      - SPRING_DATASOURCE_PASSWORD=sght123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    networks:
      - sght-net

networks:
  sght-net:
    driver: bridge