version: '3'
services:
  postgres-sght:
    container_name: postgres-sght
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hanamichi
      POSTGRES_DB: sght-db
    networks:
      - sght-net

  frontend-sght:
    container_name: frontend-sght
    build: ../front-sght/.
    ports:
      - 5174:80
    networks:
      - sght-net

  spring-sght:
    build: .
    container_name: back-spring
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hanamichi
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-sght:5432/sght-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=hanamichi
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - postgres-sght
    networks:
      - sght-net

networks:
  sght-net:
    driver: bridge